### ISSUE TITLE
Push to NPM for "send" dependency update

### ISSUE THREAD

**Issue by jameswilddev** [nikmartin/simple-static#1]
I see that the package.json in this repository has a version of "0.0.9" with a dependency on version "0.16.2" of "send".  However, only version "0.0.8" is available on NPM, which uses older version "0.12.2", which itself depends on a number of older packages which now have known security vulnerabilities.

Would it be possible to get 0.0.9 pushed to NPM?

Thanks,
  James.

**Comment by nikmartin** [comment]
Done! Also this release adds basic https/SSL support.

fixed by SHA: 69ca37f2a5a55da19bd48c567a92fff7165e5ac6
